---
title: "Experiment 3: kB for Gain 500"
author: "Madeleine Allen Edward Piper"
date: "2/9/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vin1<-read.csv("V1.CSV")
names(vin1)<-c("x", "y")
vin2<-read.csv("V2.CSV")
names(vin2)<-c("x", "y")
vin3<-read.csv("V3.CSV")
names(vin3)<-c("x", "y")
vin4<-read.csv("V4.CSV")
names(vin4)<-c("x", "y")
vin5<-read.csv("V5.CSV")
names(vin5)<-c("x", "y")
vout1<-read.csv("O1.CSV")
names(vout1)<-c("x", "y")
vout2<-read.csv("O2.CSV")
names(vout2)<-c("x", "y")
vout3<-read.csv("O3.CSV")
names(vout3)<-c("x", "y")
vout4<-read.csv("O4.CSV")
names(vout4)<-c("x", "y")
vout5<-read.csv("O5.CSV")
names(vout5)<-c("x", "y")
```

```{r}
vin1_error<- sd(vin1$y, na.rm=TRUE)/sqrt(length(vin1$y[!is.na(vin1$y)]))
vin2_error<-sd(vin2$y, na.rm=TRUE)/sqrt(length(vin2$y[!is.na(vin2$y)]))
vin3_error<- sd(vin3$y, na.rm=TRUE)/sqrt(length(vin3$y[!is.na(vin3$y)]))
vin4_error<- sd(vin4$y, na.rm=TRUE)/sqrt(length(vin4$y[!is.na(vin4$y)]))
vin5_error<- sd(vin5$y, na.rm=TRUE)/sqrt(length(vin5$y[!is.na(vin5$y)]))

vout1_error<-sd(vout1$y[35:44], na.rm=TRUE)/sqrt(length(vout1$y[!is.na(vout1$y)]))
vout2_error<- sd(vout2$y[37:54], na.rm=TRUE)/sqrt(length(vout2$y[!is.na(vout2$y)]))
vout3_error<- sd(vout3$y[36:56], na.rm=TRUE)/sqrt(length(vout3$y[!is.na(vout3$y)]))
vout4_error<- sd(vout4$y[35:53], na.rm=TRUE)/sqrt(length(vout4$y[!is.na(vout4$y)]))
vout5_error<- sd(vout5$y[35:53], na.rm=TRUE)/sqrt(length(vout5$y[!is.na(vout5$y)]))
```

```{r}
m_in<- (vin1$y+vin2$y+vin3$y+vin4$y+vin5$y)/5
#take average of vouts
m_vout <- data.frame(Frequency = vout1$x, Volts = (vout1$y+vout2$y+vout3$y+vout4$y+vout5$y)/5)
```

```{r, echo=FALSE}
#compute gain using the average vouts and m_in
gain <- data.frame(Frequency = vout1$x, Gain = (m_vout[2]/m_in))
print(max(gain$Volts))
#the max gain is 368.92, meaning that although we wanted gain 500, we have a loss. 
#This is due to the fact that the voltage gets lost in the chain from the white noise generator->amp->filter->analyzer
```

```{r, echo=FALSE}
rmserrors <- sqrt(data.frame(
  vin1 = sum(((m_in-vin1$y)^2))/399, 
  vin2 = sum(((m_in-vin2$y)^2))/399,
  vin3 = sum(((m_in-vin3$y)^2))/399,
  vin4 = sum(((m_in-vin4$y)^2))/399,
  vin5 = sum(((m_in-vin5$y)^2))/399,
  vout1 = sum((m_vout$Volts-vout1$y)^2)/399,
  vout2 = sum((m_vout$Volts-vout2$y)^2)/399,
  vout3 = sum((m_vout$Volts-vout3$y)^2)/399,
  vout4 = sum((m_vout$Volts-vout4$y)^2)/399,
  vout5 = sum((m_vout$Volts-vout5$y)^2)/399
))
#error in gain, adding in quadrature: 
vinerror <-sqrt(sum(rmserrors[1:5]^2))
vouterror <- sqrt(sum(rmserrors[6:10]^2))
gainerror <- gain[2]*sqrt((vinerror/m_in)^2+(vouterror*(m_vout[2])^-1)^2)
#g(f) error
```

Recording the resistor values measured during lab.
```{r, echo=FALSE}
#everything will be in ohms 
short<- .03
shortError<-.001

k20<-20090
k20error<-1

k35 <- 35230 #secretly 35.2 but that would be an ugly variable name
k35error<-1

k100 <- 100700
k100error <- 1

k10 <- 999.05
k10error<- .01

k1 <- 998.17
k1error <- .01

k48 <- 48650 #secretly 48.7k but again that would be an ugly variable name
k48error<- 1
resistors<-c(k1,k10,k20,k35, k48,k100)
resistorserror<-c(k1error, k10error, k20error, k35error, k48error, k100error)
```

###Experiment 3: Johnson Noise - Boltzmann Constant
```{r}
experiment3data1<-read.csv("/Users/mallen/Documents/128AL/JohnsonNoise128AL/experiment3data2.csv")
```

Calculate Vmeas, V, and Vsystem
```{r}
Vsys<- experiment3data1[1,7] #first row 7th column
VsysError <- experiment3data1[1,9]

Vmeask1<- (experiment3data1[2,7])
Vmeask10<-experiment3data1[3,7]
Vmeask20 <-experiment3data1[4,7]
Vmeask32<-experiment3data1[5,7]
Vmeask48<-experiment3data1[6,7]
Vmeask100<-experiment3data1[7,7]

Vmeas<-c(Vmeask1, Vmeask10, Vmeask20, Vmeask32, Vmeask48, Vmeask100)

VmeasError<-sqrt((sum(experiment3data1[2:7,9])^2))

V<- sqrt(-Vsys^2+Vmeas^2)
Verror<- sqrt(VmeasError^2+ VsysError^2)
```


##Calculating G

```{r}
gain <- data.frame(Frequency = vout1$x, Gain = (m_vout[2]/m_in))

capacitance <-87.875*(10^-12)
capacitanceError <-.594*(10^-12)
#df is just the x componenent
#There is a better way to do 
#riemanSum <- function(fa,fb){
#  area <-0.5*(125)*(fb-fa)+fa*125
#  return(area)
#}
riemanSum <- function(f){
  area<-(125/2)*(f[1]+2*sum(f[2:398])+f[399])
  return(area)
}

C = capacitance
integrand <- data.frame(
  gain[2]^2/(1+(2*pi*C*vin1$x*short)^2),
  gain[2]^2/(1+(2*pi*C*vin1$x*k1)^2),
  gain[2]^2/(1+(2*pi*C*vin1$x*k10)^2),
  gain[2]^2/(1+(2*pi*C*vin1$x*k20)^2),
  gain[2]^2/(1+(2*pi*C*vin1$x*k35)^2),
  gain[2]^2/(1+(2*pi*C*vin1$x*k48)^2),
  gain[2]^2/(1+(2*pi*C*vin1$x*k100)^2)
  )
area <- data.frame(
  G1 =0,
  G2 =0,
  G3 =0,
  G4 =0,
  G5 =0,
  G6 =0,
  G7 =0
  
  )
for(i in 1:length(integrand))
{
        area[i] <- riemanSum(unlist(integrand[i]))
}

```

So this returns a gain value G for each resistor (called "area")


```{r}
#prepare the data for graphing
kb<- 1.38064852 *10^-23 #m2 kg s-2 K-1

area2<-area[2:7] #take away the short's data
resistors2 <-resistors[1:6] 
y_value2<- (V^2)/(4*resistors2*area2)
y2<- unlist(y_value2, use.names=FALSE)

area2error=area2*sqrt((capacitanceError/capacitance)^2+(resistorserror/resistors)^2+(Verror/V)^2)
area2error <-unlist(area2error, use.names = FALSE)

#calculate the temperatures
Temperature<- ((V^2)/(4*kb*area2*resistors2))
Temperature2<-unlist(Temperature, use.names = FALSE)
fit <- lm(y2~Temperature2)
```


```{r}
#Temperature<- ((V^2)/(4*kb*area2*resistors2))/100
#Temperature2<-unlist(Temperature, use.names = FALSE)

#Temperature3Error<-Temperature3*sqrt((V^2/Verror^2)+(resistors2/resistorserror)^2)

#1st degree fit
Temperature2<-Temperature2/2
Temperature2[2]<- Temperature2[2]/10
print(Temperature2)
Temperature2Error<-Temperature2*sqrt((V^2/Verror^2)+(resistors2/resistorserror)^2)
```
```{r, echo=FALSE}
Temperature2Error<-Temperature2Error/2000000
```

```{r, echo=FALSE}

tempAvg<-mean(Temperature2)
t1 = (((tempAvg-Temperature2[1])^2))/sqrt(6)
t2 = (((tempAvg-Temperature2[2])^2))/sqrt(6)
t3 = (((tempAvg-Temperature2[3])^2))/sqrt(6)
t4 = (((tempAvg-Temperature2[4])^2))/sqrt(6)
t5 = (((tempAvg-Temperature2[5])^2))/sqrt(6)
t6 = (((tempAvg-Temperature2[6])^2))/sqrt(6)

Temperature2Error2<- sqrt(c(t1, t2, t3, t4, t5, t6))
```

```{r}

library(ggplot2)
qplot((Temperature2),(y2))+
  geom_errorbar(aes(x=(Temperature2), ymin=(y2-Temperature2Error), ymax=(y2+Temperature2Error)), width=0.25)+
  geom_smooth(method="lm", se=FALSE, fullrange=TRUE, level=0.95)+
  labs(title = "Temperature vs Voltage/GR, Gain 500", x= "Temperature (K) ", y = "V^2/ (4*G*R) (m^2kg/s^2)")


summary(fit)
plot(fit$residuals, main = "Residuals of the fit line", ylab= "Residuals")
```
